### PR TITLE
[WIP] Sharing tickets to respect rich comments

### PR DESCRIPTION
**Pull request by aghassipour**
When this is deployed, this needs to deployed as well: https://github.com/zendesk/zendesk/pull/22948

### CODE REVIEW

**Comment by maxmccal** [comment]
@zendesk/boxoffice Can anyone take a look at this?

**Comment by shajith** [comment]
@aghassipour: right now, all ticket comments should have a proper `body` and `html_body`, right? I.e, all comments are `rich`, in that sense. Could we just add `html_body` to the payload, and prefer that at the receiving end when constructing a comment, like the ticket API does?

**Comment by aghassipour** [comment]
@shajith want to spend 15 minutes looking through this together?

**Comment by shajith** [comment]
@aghassipour yes please! not sure where to ping you tho

**Comment by aghassipour** [comment]
I'm on 3rd. Can also come to wherever you are.

**Comment by shajith** [comment]
@aghassipour: at PA today, hangouts or something?

**Comment by aghassipour** [comment]
No rush. Maybe tomorrow?

**Comment by shajith** [comment]
@kencheeto @mwerner: this is in the overlap of rich text support in comments, and ticket sharing. We need to present the html version of each comment in the payload shared between accounts engaged in a ticket sharing agreement. Can I get some eyes on this?

cc: @adam-hart, who @pdeuter claims is all up in ticket sharing code these days (PTO until Monday).

**Comment by mwerner** [comment]
Since the attr is being added using `fields` it looks like it'll get included in the json payload between accounts for free: https://github.com/zendesk/ticket_sharing/blob/master/lib/ticket_sharing/base.rb#L33

**Comment by kencheeto** [comment]
FWIW, I remember the Jira integration breaking when we added a new field. Have we talked to our external ticket sharing partners?

**Comment by aghassipour** [comment]
@kencheeto if we've talked to our external ticket sharing partners re. this change, you mean?

**Comment by kencheeto** [comment]
@aghassipour Yeah, exactly, just something worth poking them about (as well as any other external partners).

We should also verify that our end of ticket sharing also safely accepts html_body, then (like @shajith already said) do the work to prefer html_body if present. Seems fine otherwise.

**Comment by aghassipour** [comment]
Im confused, maybe I need some context. Why would we need to talk to our partners to fix a bug? Will fixing it break existing behaviour? Maybe it's the wrong fix then. To recap, zendesk to zendesk sharing confuses the formatting.

markdown_weirdness_for_shared_tickets_-_alexander_zendesk_com_-_zendesk_mail

**Comment by kencheeto** [comment]
@aghassipour if we pull this change downstream into Zendesk, we will begin adding an `html_body` field to all comment json payloads that are shared to ticket sharing partners.

In the past, sharing agreements with Jira broke because we added new fields to the agreements json. I don't _know_ that adding new fields to the comment payload will break anything, but it has in the past so I would at least want to check with Atlassian folks that their sharing endpoint can handle an extra json key. They may also want to do something with html_body, if that's interesting to them.

**Comment by aghassipour** [comment]
"We should also verify that our end of ticket sharing also safely accepts html_body, then (like @shajith already said) do the work to prefer html_body if present. Seems fine otherwise."

@mwerner where is that happening in the code?

**Comment by mwerner** [comment]
That's an excellent question. I've been reading the code over today and so far it seems like this would be a fine change. I have to caution I'm completely new to the ticket sharing code, so I'm pretty unfamiliar with edge cases. I think most of this was written by Josh and Mick. I'll keep reading. I'm also going to try to see if I can get your PR setup locally.

**Comment by aghassipour** [comment]
Thanks. @pschambacher seems to have been involved in the ticket sharing branch recently as well.

**Comment by pschambacher** [comment]
This looks fine as is. Now we could always send html_body as the body part. That said I'm unsure how JIRA would react to this.

**Comment by mwerner** [comment]
The Zendesk side of things look to be fine with this change. Regarding the reception of `html_body`, you've got that covered with zendesk/zendesk#22948. I tested it out and it seemed to be including the attribute as expected.

I brought this to the attention of @yuri4zendesk and we're looking into possible integration implications for Jira.

**Comment by aghassipour** [comment]
Awesome, thanks @mwerner

**Comment by yuri4zendesk** [comment]
Hi Alexander,

The new JIRA integration my team is working on, doesn't use ticket sharing
but the older version developed for us by a partner, does.
We're not familiar with their code, but I can ask them if this is going to
be a problem.

I'll update as soon as I hear back from them.





On Fri, May 13, 2016 at 9:35 AM, Alexander Aghassipour <
notifications@github.com> wrote:

> Awesome, thanks @mwerner <https://github.com/mwerner>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/ticket_sharing/pull/18#issuecomment-218915427>
>



-- 
Yuri Mylis
Product Manager
Zendesk <http://www.zendesk.com/>
Skype: zendesk.ymylis

**Comment by mwerner** [comment]
@yuri4zendesk Any updates here on the Jira integration? Also, do you have any information about the difference in number of users using the various Jira integrations?

**Comment by yuri4zendesk** [comment]
Hi Alexander and Mathew,

I heard back from the partner, they say that the change should not break
the JIRA integration, but I suggest you roll out the change behind arturo in
case there are unforeseen implications.



On Wed, May 18, 2016 at 4:56 AM, Matthew Werner <notifications@github.com>
wrote:

> @yuri4zendesk <https://github.com/yuri4zendesk> Any updates here on the
> Jira integration? Also, do you have any information about the difference in
> number of users using the various Jira integrations?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesk/ticket_sharing/pull/18#issuecomment-219818250>
>



-- 
Yuri Mylis
Product Manager
Zendesk <http://www.zendesk.com/>
Skype: zendesk.ymylis

**Comment by mwerner** [comment]
@aghassipour It looks like that's a +1. We'll need to bump the version of the ticket_sharing gem, that can be done in this PR or in a separate one. We'll use that newly created version number in the zendesk/zendesk#22948 PR instead of specifying your git path.

**Comment by aghassipour** [comment]
@mwerner can you please help me do that, thanks.

@shajith @kencheeto are you comfortable with this going live?

**Comment by mwerner** [comment]
@aghassipour No problem, after this is merged I'll follow up with a version bump to zendesk/ticket_sharing and update zendesk/zendesk#22948

**Comment by shajith** [comment]
@aghassipour: I'm fine with it going live, maybe give us a heads up when this lands in classic?

cc: @MayraLP

**Pull request merged**
