### PR TITLE
Remove bare Net HTTP and make compatible with Faraday clients.

### PR DESCRIPTION
**Pull request by pschambacher**
:octopus::computer:

/cc @grosser @anamartinez @jcheatham @gabetax 

Also interested in @ciaranarcher 's opinion since we're aiming to use our very own custom Faraday connection for this.

### Description
Remove Net::HTTP implementation in favor of Faraday clients.

This should allow us to configure the gem with a Faraday connection and use it, benefiting from all the middlewares coming with it.

I'm just a bit doubtful about the SSL-bit since Faraday doesn't exactly allow us to change the configuration on the fly but I think it should work.

### Steps to merge
* [ ] :+1: from the team

### Risks
* High: this will be a major bump, the entire gem might not be working at all (I'm not entirely sure how much we can trust the test suite)

### CODE REVIEW

**Comment by grosser** [comment]
👍 
FYI wanted to recommend hurley ... but apparently that is dead now too :D 
https://github.com/lostisland/hurley/issues/43

**Comment by jcheatham** [comment]
Yeah, definitely major bump; as a sanity check I'd recommend running a branch of classic with this, though unfortunately a most of the tests there are stubbed anyway, so it probably won't help *much*... no obvious red flags stand out to me, will take another pass but looks 👍

**Comment by jish** [comment]
https://www.mikeperham.com/2016/02/09/kill-your-dependencies/

Josh

**Comment by ciaranarcher** [comment]
Thanks for pinging me on this!

If you are going this far, why not use the [recently merged](https://github.com/zendesk/zendesk/pull/22200) Kragle [connection](https://github.com/zendesk/zendesk/blob/4b0f63237823b5455de9ee71766bd2e605db1fd5/lib/kragle_connection.rb) so you get metrics etc for free 😍  

The service in question could just be called "ticket_sharing".  You could set up a ticket sharing "client" wrapping a Kragle connection (which is just a faraday connection with some defaults and metrics) which will set default headers / timeouts etc.

**Comment by pschambacher** [comment]
@ciaranarcher I'd love to but there a problem of public vs private gem here
:) that's why I defined TicketSharing.connection

**Pull request merged**
